package com.yaneodex.desktop.ui

import com.yaneodex.core.state.AppLanguage

data class DesktopStrings(
    val appTitle: String,
    val navHome: String,
    val navSearch: String,
    val navPlaylists: String,
    val navLibrary: String,
    val navImport: String,
    val languageLabel: String,
    val topEyebrow: String,
    val topTitle: String,
    val searchPlaceholder: String,
    val runAction: String,
    val sectionPlaylists: String,
    val sectionRecentLibrary: String,
    val sectionParserResults: String,
    val sectionLibrary: String,
    val sectionOcrSettings: String,
    val sectionImportReview: String,
    val sectionUpNext: String,
    val sectionNowShaping: String,
    val sectionPlaylist: String,
    val sectionParser: String,
    val sectionOcr: String,
    val createPlaylistPlaceholder: String,
    val renamePlaylistPlaceholder: String,
    val createAction: String,
    val renameAction: String,
    val addFoldersAction: String,
    val refreshAction: String,
    val chooseScreenshotsAction: String,
    val playLaneAction: String,
    val removeAction: String,
    val addAction: String,
    val previewAction: String,
    val downloadAction: String,
    val parserReadyChip: String,
    val ocrReadyChip: String,
    val windowsBuildChip: String,
    val queueLabel: String,
    val shuffleLabel: String,
    val parserLabel: String,
    val ocrLabel: String,
    val noTrackSelected: String,
    val noTrackSelectedSubtitle: String,
    val noParserResults: String,
    val queueItemsSuffix: String,
    val shuffleOn: String,
    val shuffleOff: String,
    val ocrServerLabel: String,
    val ocrServerPlaceholder: String,
    val bearerTokenLabel: String,
    val bearerTokenPlaceholder: String,
    val rootsHeader: String,
    val noRootsConfigured: String,
    val playlistFocusEyebrow: String,
    val moodSelectedEyebrow: String,
    val moodSelectedSubtitle: String,
    val parserCandidateEyebrow: String,
    val parserResultsIdle: String,
    val importReadyMessage: String,
    val onboardingEyebrow: String,
    val onboardingTitle: String,
    val onboardingSubtitle: String,
    val onboardingPrimaryAction: String,
    val onboardingSecondaryAction: String,
    val onboardingParserAction: String,
    val emptyStateTitle: String,
)

fun desktopStrings(language: AppLanguage): DesktopStrings = when (language) {
    AppLanguage.RU -> DesktopStrings(
        appTitle = "YaNeoDex Desktop",
        navHome = "Главная",
        navSearch = "Поиск",
        navPlaylists = "Плейлисты",
        navLibrary = "Библиотека",
        navImport = "Импорт",
        languageLabel = "Язык",
        topEyebrow = "",
        topTitle = "Музыка",
        searchPlaceholder = "Поиск треков",
        runAction = "Искать",
        sectionPlaylists = "Плейлисты",
        sectionRecentLibrary = "Недавно добавлено",
        sectionParserResults = "Результаты",
        sectionLibrary = "Библиотека",
        sectionOcrSettings = "OCR",
        sectionImportReview = "Совпадения",
        sectionUpNext = "Дальше",
        sectionNowShaping = "Сейчас",
        sectionPlaylist = "Плейлист",
        sectionParser = "Парсер",
        sectionOcr = "OCR",
        createPlaylistPlaceholder = "Новый плейлист",
        renamePlaylistPlaceholder = "Переименовать",
        createAction = "Создать",
        renameAction = "Сохранить",
        addFoldersAction = "Папки",
        refreshAction = "Обновить",
        chooseScreenshotsAction = "Скриншоты",
        playLaneAction = "Играть",
        removeAction = "Убрать",
        addAction = "Добавить",
        previewAction = "Слушать",
        downloadAction = "Скачать",
        parserReadyChip = "Parser",
        ocrReadyChip = "OCR",
        windowsBuildChip = "Windows",
        queueLabel = "Очередь",
        shuffleLabel = "Перемешать",
        parserLabel = "Парсер",
        ocrLabel = "OCR",
        noTrackSelected = "Ничего не играет",
        noTrackSelectedSubtitle = "Выбери трек",
        noParserResults = "Ничего не найдено",
        queueItemsSuffix = "треков",
        shuffleOn = "Вкл",
        shuffleOff = "Выкл",
        ocrServerLabel = "OCR URL",
        ocrServerPlaceholder = "https://host",
        bearerTokenLabel = "Token",
        bearerTokenPlaceholder = "Необязательно",
        rootsHeader = "Папки",
        noRootsConfigured = "Папки не выбраны",
        playlistFocusEyebrow = "",
        moodSelectedEyebrow = "",
        moodSelectedSubtitle = "",
        parserCandidateEyebrow = "",
        parserResultsIdle = "Запусти поиск",
        importReadyMessage = "Готово",
        onboardingEyebrow = "",
        onboardingTitle = "Добавь музыку",
        onboardingSubtitle = "",
        onboardingPrimaryAction = "Папки",
        onboardingSecondaryAction = "Обновить",
        onboardingParserAction = "Поиск",
        emptyStateTitle = "Пусто",
    )
    AppLanguage.EN -> DesktopStrings(
        appTitle = "YaNeoDex Desktop",
        navHome = "Home",
        navSearch = "Search",
        navPlaylists = "Playlists",
        navLibrary = "Library",
        navImport = "Import",
        languageLabel = "Language",
        topEyebrow = "",
        topTitle = "Music",
        searchPlaceholder = "Search tracks",
        runAction = "Search",
        sectionPlaylists = "Playlists",
        sectionRecentLibrary = "Recently Added",
        sectionParserResults = "Results",
        sectionLibrary = "Library",
        sectionOcrSettings = "OCR",
        sectionImportReview = "Matches",
        sectionUpNext = "Up Next",
        sectionNowShaping = "Now",
        sectionPlaylist = "Playlist",
        sectionParser = "Parser",
        sectionOcr = "OCR",
        createPlaylistPlaceholder = "New playlist",
        renamePlaylistPlaceholder = "Rename",
        createAction = "Create",
        renameAction = "Save",
        addFoldersAction = "Folders",
        refreshAction = "Refresh",
        chooseScreenshotsAction = "Screenshots",
        playLaneAction = "Play",
        removeAction = "Remove",
        addAction = "Add",
        previewAction = "Preview",
        downloadAction = "Download",
        parserReadyChip = "Parser",
        ocrReadyChip = "OCR",
        windowsBuildChip = "Windows",
        queueLabel = "Queue",
        shuffleLabel = "Shuffle",
        parserLabel = "Parser",
        ocrLabel = "OCR",
        noTrackSelected = "Nothing playing",
        noTrackSelectedSubtitle = "Pick a track",
        noParserResults = "Nothing found",
        queueItemsSuffix = "items",
        shuffleOn = "On",
        shuffleOff = "Off",
        ocrServerLabel = "OCR URL",
        ocrServerPlaceholder = "https://host",
        bearerTokenLabel = "Token",
        bearerTokenPlaceholder = "Optional",
        rootsHeader = "Folders",
        noRootsConfigured = "No folders selected",
        playlistFocusEyebrow = "",
        moodSelectedEyebrow = "",
        moodSelectedSubtitle = "",
        parserCandidateEyebrow = "",
        parserResultsIdle = "Run a search",
        importReadyMessage = "Ready",
        onboardingEyebrow = "",
        onboardingTitle = "Add music",
        onboardingSubtitle = "",
        onboardingPrimaryAction = "Folders",
        onboardingSecondaryAction = "Refresh",
        onboardingParserAction = "Search",
        emptyStateTitle = "Empty",
    )
}
